CC = gcc
CFLAGS = -m32 -Wall -fno-pic
LDFLAGS = -m32 -no-pie
LDLIBS = -lso_loader

.PHONY: build
build: so_exec so_test_prog heart

so_exec: exec.o
	$(CC) $(LDFLAGS) -L. -Wl,-Ttext-segment=0x20000000 -o $@ $< $(LDLIBS)

exec.o: exec/exec.c
	$(CC) $(CFLAGS) -Iloader -o $@ -c $<

so_test_prog: test_prog.o
	$(CC) $(LDFLAGS) -nostdlib -o $@ $<

test_prog.o: test_prog/hello.S
	$(CC) $(CFLAGS) -o $@ -c $<

heart: heart.o
	$(CC) $(LDFLAGS) -static -o $@ $<

heart.o: heart/heart.c
	$(CC) $(CFLAGS) -static -o $@ -c $<

.PHONY: clean
clean:
	-rm -f exec.o so_exec so_test_prog test_prog.o heart heart.o
